### ISSUE TITLE
Importing jest globals fails the integration test

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/coffee-store#3]
Just in case someone else runs into the same error, in Episode 4 running the integration test with the jest global imports throws 
`Do not import  @jest/globals outside of the Jest test environment`

No errors without the import.

- Windows 10 (Windows Subsystem for Linux 2)
- nodejs: v14.13.1
- npm: 6.14.8

![image](https://user-images.githubusercontent.com/204049/95539659-8f6d4b80-09b4-11eb-9e49-9b7faad4a428.png)

**Comment by mikebroberts** [comment]
That's very weird. I saw that, I think, when I had that require in a file that wasn't a test file, but it's ok for me otherwise. I just explicitly tried with the same nodejs and npm versions as you, and checked out the episode-4 tag to make doubly sure, but it still works for me. Only difference from what you describe is that I'm not on Windows.

**Comment by asunar** [comment]
Windows 10 is the host, the execution environment is Ubuntu (via WSL 2). I was hoping to avoid windows only issues by running in Ubuntu.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
